# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e21019f2ee191b464643e6ff35d96036e43afb83dfebd8d56ff028db88af53a23721b4efc34ee0302d84d8136c86c2ea3c88549677ace5a14e725bc6a79ebe

test:
  secret_key_base: fae9d5058b61fd85b7436d7660b2304cb912a3dba877c3afeab49068fdced0a97f9822cb9e1a27fe65aec89cd92889ca637e4567830116564f240e00e6e90c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
